SELECT SEC_IND_CODE, COUNT(*) as Company_Count FROM asharesecindustriesclass GROUP BY SEC_IND_CODE;
SELECT COMP_NAME, MAX(TYPE_CODE) AS Maximum_Permits FROM cfundadmpermitschedule GROUP BY COMP_NAME ORDER BY Maximum_Permits DESC LIMIT 1;
SELECT RATING_INTERVAL, COUNT(S_INFO_WINDCODE) FROM cmfundwindrating WHERE STARLEVEL >= 4.0 GROUP BY RATING_INTERVAL;
SELECT S_INFO_WINDCODE, AVG(S_INC_TRANSFERPRIPER) FROM ashareincquantityprice WHERE S_INC_ISCOMPLETED = 1 GROUP BY S_INFO_WINDCODE
SELECT S_INFO_WINDCODE, S_INFO_INDEXWEG FROM chinamutualfundbenchmark WHERE S_INFO_BGNDT >= '20180101';
SELECT CHANGE_DT, S_SHARE_FREESHARES FROM asharefreefloat WHERE S_INFO_WINDCODE = '300416.SZ';
SELECT WORKING_DATE FROM GLOBALWORKINGDAY WHERE COUNTRY_CODE='SGP';
SELECT S_INFO_COMPNAME, MAX(SALESAMOUNT) as MAX_SALES FROM top5byoperatingincome WHERE CRNCY_CODE = 'CNY';
SELECT S_INFO_CODE, AVG(MARKET_VALUE) as Average_Market_Value FROM fundbondportfolio GROUP BY S_INFO_CODE;
SELECT F_INFO_FUNDMANAGER FROM CHFUNDMANAGER WHERE F_INFO_MANAGER_LEAVEDATE IS NOT NULL
SELECT S_INFO_WINDCODE, MAX(S_SURVEYDATE) as Most_Recent_Date FROM ashareisactivity GROUP BY S_INFO_WINDCODE;
SELECT S_INFO_SECTYPENAME, MAX(S_INFO_LOT_SIZE) as Max_Lot_Size FROM cfundwindcustomcode GROUP BY S_INFO_SECTYPENAME;
SELECT CURRENCY_CODE, SUM(ARREARS) as TOTAL_ARREARS FROM asharemajorreceivables GROUP BY CURRENCY_CODE
SELECT S_CAPITALOPERATION_COMPANYNAME, VOTING_RIGHTS, S_CAPITALOPERATION_PCT FROM asharecompanyholdshares WHERE VOTING_RIGHTS IS NOT NULL GROUP BY VOTING_RIGHTS, S_CAPITALOPERATION_PCT HAVING COUNT(*) > 1;
SELECT S_INFO_COMPCODE, MAX(TOTAL_AMOUNT) as MAX_LOANS FROM bankloan5lclassification WHERE REPORT_PERIOD=(SELECT MAX(REPORT_PERIOD) FROM bankloan5lclassification)
SELECT FUNDMANAGER_ID, WORSTTOTRETURN_6M FROM chinamfmperformance ORDER BY WORSTTOTRETURN_6M ASC LIMIT 3;
SELECT S_INFO_WINDCODE, MAX(F_INFO_REDEMPTION_CAP) as Max_Redemption_Cap FROM chinaetfpchredmlist WHERE TRADE_DT LIKE '2016%' GROUP BY S_INFO_WINDCODE ORDER BY Max_Redemption_Cap DESC LIMIT 10;
SELECT S_CON_WINDCODE, S_CON_OUTDATE FROM aindexmemberscitics3 WHERE CUR_SIGN = 0 ORDER BY S_CON_OUTDATE DESC;
SELECT SUM(VALUE) as total_value FROM qdiiindportfolio WHERE IND = '信息技术' AND END_DT = '20161231';
SELECT B_INFO_HOLDER, B_INFO_HOLDAMOUNT FROM cmfholder WHERE B_ISSUER_SHARECATEGORY = 2 ORDER BY B_INFO_HOLDAMOUNT DESC LIMIT 5;
SELECT SUM(AMOUNT) as Total_Guarantee FROM ashareguarantee
SELECT * FROM suspendsecvaluation WHERE S_INFO_WINDCODE = '600120.SH'
SELECT S_CON_WINDCODE, MAX(ANN_DATE) AS most_recent_announcement FROM AINDEXALTERNATIVEMEMBERS WHERE S_CON_WINDCODE = '530060.SH'
SELECT S_HOLDER_NAME, S_HOLDER_TYPE, ORDQTY FROM ashareplacementdetails ORDER BY ANN_DT DESC LIMIT 5
SELECT S_INFO_COMPCODE, MAX(BAD_DEBT_PREPARATION) as MAX_BAD_DEBT_PREPARATION FROM ashareagingstructure WHERE REPORT_PERIOD = '20171231' GROUP BY S_INFO_COMPCODE ORDER BY MAX_BAD_DEBT_PREPARATION DESC LIMIT 5
SELECT S_INFO_WINDCODE, DVD_PAYOUT_DT, CASH_DVD_PER_SH_AFTER_TAX FROM asharedividend WHERE REPORT_PERIOD LIKE '2018%' ORDER BY CASH_DVD_PER_SH_AFTER_TAX DESC;
SELECT F_INFO_MANAGER_GENDER, COUNT(*) AS gender_count FROM chinamutualfundmanager GROUP BY F_INFO_MANAGER_GENDER;
SELECT S_INFO_COMPCODE FROM ashareguaranteestatistics WHERE VIOLATION_AMOUNT_GUARANTEE > 0;
SELECT S_INFO_WINDCODE, MAX(TOTAL_LOAN) as Max_Total_Loan FROM asharebankindicator WHERE REPORT_PERIOD LIKE '2019%' GROUP BY S_INFO_WINDCODE ORDER BY Max_Total_Loan DESC LIMIT 1;
SELECT ENTRY_DT, WIND_IND_CODE FROM ashareindustriesclass WHERE WIND_CODE = '600634.SH' ORDER BY ENTRY_DT
SELECT S_INFO_WINDCODE, MAX(CAP_ADEQUACY_RATIO_LIFE) AS Max_Cap_Adequacy_Life, MIN(CAP_ADEQUACY_RATIO_LIFE) AS Min_Cap_Adequacy_Life FROM ashareinsuranceindicator GROUP BY S_INFO_WINDCODE ORDER BY Max_Cap_Adequacy_Life DESC;
SELECT SCOPE, SUM(VALUE) as Total_Investment FROM qdiiscopeportfolio GROUP BY SCOPE ORDER BY Total_Investment DESC;
SELECT S_INFO_WINDCODE FROM cmfsubredfee WHERE AMOUNTDOWNLIMIT > 100 AND USED = 1;
SELECT S_INFO_COMPANYNAME, ACC_FIRM FROM ipocomprfa WHERE SPONSOR = '华创证券有限责任公司';
SELECT DISTINCT S_INFO_COMPCODE FROM asHaretaxrate WHERE TAX_RATE > 20.0 AND REPORT_PERIOD = '20151231'
SELECT S_INFO_WINDCODE FROM cfundstylecoefficient WHERE STYLE_COEFFICIENT > 0.5 AND S_CHANGE_DATE LIKE '2017%';
SELECT TRADE_DT, SUM(S_DQ_VOLUME) as TOTAL_VOLUME FROM cmfindexeod WHERE TRADE_DT = '20161028' GROUP BY TRADE_DT
SELECT S_INFO_WINDCODE, S_INC_SUBJECT, S_INC_INITEXECPRI FROM ashareincdescription WHERE S_INC_INITEXECPRI > 10.0;
SELECT S_INFO_WINDCODE, F_PRT_ENDDATE, F_PRT_BONDONAV, F_PRT_STOCKONAV FROM chinamutualfundassetportfolio WHERE F_PRT_ENDDATE = '20180630' AND F_PRT_BONDONAV > F_PRT_CASHTONAV AND F_PRT_STOCKONAV > 50;
SELECT * FROM cmfrisklevel WHERE RISK_LEVEL = '中高风险'
SELECT AVG(GUARANT_FEE) FROM cpfunddescription WHERE GUARANTOR = '深圳市高新投集团有限公司';
SELECT S_INFO_COMPCODE, S_FA_GR_TTM FROM asharettmhis ORDER BY S_FA_GR_TTM DESC LIMIT 3;
SELECT REPORT_PERIOD, ITEM_NAME, AMOUNT_CURRENT_ISSUE, AMOUNT_PREVIOUS_PERIOD FROM ASHAREGOVERNMENTGRANTS WHERE ITEM_NAME LIKE '%收入%' AND AMOUNT_CURRENT_ISSUE > AMOUNT_PREVIOUS_PERIOD;
SELECT S_INFO_WINDCODE, SUBSTRIPTION_PRICE, PCH_CODE FROM lofpchredm WHERE S_INFO_EXCHMARKET = '上海' AND REDM_START_DT LIKE '2016%'
SELECT F_INFO_WINDCODE, F_UNIT_RPENDDATE, F_NAV_RETURN FROM cmfquarterlyfinancialindicator ORDER BY F_NAV_RETURN DESC LIMIT 5
SELECT S_INFO_WINDCODE, S_DIV_OBJECT FROM asharedividend WHERE S_DIV_CHANGE = '2017';
SELECT * FROM ashareholdersmeeting WHERE IS_INTNET = 1;
SELECT SUM(TRADE_VALUE) FROM mergerevent WHERE IS_CONTROL_CHANGE = 1;
SELECT S_HOLDER_NAME, SUM(S_SHARE_LST) AS TOTAL_SHARES FROM asharecomprestricted GROUP BY S_HOLDER_NAME ORDER BY TOTAL_SHARES DESC LIMIT 1
SELECT S_INFO_LISTBOARDNAME, AVG(S_INFO_OUTSTANDINGBALANCE) as Avg_Outstanding_Balance FROM LOFDESCRIPTION GROUP BY S_INFO_LISTBOARDNAME;
SELECT MAX(MA_20D) as highest_value, MIN(MA_20D) as lowest_value FROM ashareintensitytrend WHERE S_INFO_WINDCODE = '000584.SZ' AND TRADE_DT LIKE '2017%';
SELECT S_INFO_WINDCODE, TRADE_DT, MFI FROM ashareenergyindexadj WHERE MFI = (SELECT MAX(MFI) FROM ashareenergyindexadj)
SELECT S_HOLDER_NAME, S_HOLDER_QUANTITY FROM ashareinsideholder WHERE S_INFO_WINDCODE = '000656.SZ' ORDER BY S_HOLDER_QUANTITY DESC LIMIT 5
SELECT S_INFO_WINDCODE FROM CMFOTHERPORTFOLIO WHERE END_DT=(SELECT MAX(END_DT) FROM CMFOTHERPORTFOLIO) ORDER BY VALUE DESC LIMIT 1
SELECT S_INFO_WINDCODE, MAX(ACT_SHARESNO) as Max_Actual_Shares FROM ashareesopdescription GROUP BY S_INFO_WINDCODE ORDER BY Max_Actual_Shares DESC LIMIT 5;
SELECT DISTINCT S_INFO_COMPNAME FROM suspendsecvaluationmethod WHERE S_DQ_SUSPENDDATE > '20160101';
SELECT DISTINCT AGING FROM ashareprovisionbaddebts
SELECT S_INFO_NAME, S_INFO_CODE FROM WINDCUSTOMCODE WHERE S_INFO_SECTYPENAME = '期权';
SELECT S_INFO_WINDCODE, F_UNIT_RPENDDATE, F_UNIT_PURCHASE_TOTAL FROM chinamutualfundpchredm WHERE F_UNIT_RPENDDATE = (SELECT MAX(F_UNIT_RPENDDATE) FROM chinamutualfundpchredm) ORDER BY F_UNIT_PURCHASE_TOTAL DESC LIMIT 5
SELECT S_INFO_WINDCODE, ENDDATE, POSSTKTONAV FROM qdiiscopeportfolio WHERE ENDDATE <= '20160331' GROUP BY S_INFO_WINDCODE, ENDDATE ORDER BY POSSTKTONAV DESC;
SELECT CRNCY_CODE, SUM(INVEST_AMOUNT) FROM qfiiquotachange GROUP BY CRNCY_CODE;
SELECT S_INFO_NAME FROM aindexdescription WHERE S_INFO_PUBLISHER = '深交所';
SELECT COUNT(DISTINCT S_INFO_WINDCODE) FROM ashareinsideholder WHERE S_HOLDER_NAME = '童林芳';
SELECT DEGREE, COUNT(*) as degree_count FROM iecmemberlist GROUP BY DEGREE;
SELECT RELATED_MANAGER_NAME, REPORTED_TRADER_NAME, CHANGE_VOLUME FROM ashareinsidertrade WHERE CHANGE_VOLUME > 10000;
SELECT S_INFO_COMPNAME FROM ashareownership WHERE REMOVE_DT != '无'
SELECT AVG(EXTRACTION_RATIO) FROM ashareprovisionbaddebts WHERE REPORT_PERIOD LIKE '2016%';
SELECT F_INFO_WINDCODE, SUM(FUNDSHARE_TOTAL) as Total_Shares FROM chinamutualfundshare GROUP BY F_INFO_WINDCODE;
SELECT ENTRY_DT FROM shscmembers WHERE S_INFO_WINDCODE = '601117.SH';
SELECT TRADE_DT, S_LI_LARGEBUYRATE FROM asharel2indicators ORDER BY S_LI_LARGEBUYRATE DESC LIMIT 5
SELECT * FROM cmfcodeandsname WHERE TYPE_CODE = '111008000'
SELECT COUNT(*) FROM cmfsellingagents WHERE CUR_SIGN = 1;
SELECT AVG(I_WEIGHT) AS Average_Weight FROM aindexhs300freeweight WHERE TRADE_DT = '20150227';
SELECT CONVERT_REASON, MAX(NAV_MIN), MAX(NAV_MAX) FROM scfconvert GROUP BY CONVERT_REASON;
SELECT S_INFO_WINDCODE, MAX(S_TOTAL_PLEDGE_SHR) as Maximum_Pledged_Shares FROM ashareequitypledgeinfo GROUP BY S_INFO_WINDCODE ORDER BY Maximum_Pledged_Shares DESC;
SELECT * FROM ashareofferforoffer WHERE RESTRICTED_PURCHASING_PRICE > PURCHASING_PRICE;
SELECT S_INFO_WINDCODE FROM chinafundmajorevent WHERE S_EVENT_CATEGORYCODE = 204033005
SELECT NAME, SUM(QUANTITY*POSSTKTONAV) AS TotalValue, SUM(QUANTITY) AS TotalQuantity FROM qdiisecuritiesportfolio GROUP BY NAME ORDER BY TotalValue DESC, TotalQuantity DESC LIMIT 10
SELECT S_INFO_EFFECTIVE_DT, S_INFO_INVALID_DT FROM RALATEDSECURITIESCODE WHERE S_INFO_WINDCODE = '1572014.IB';
SELECT AVG(TOT_INC) AS Avg_Total_Income, AVG(TOT_EXP) AS Avg_Total_Expenditure, AVG(NET_PROFIT) AS Avg_Net_Profit FROM cmfincome WHERE SUBSTR(REPORT_PERIOD, 1, 4) = '2015';
SELECT * FROM chfunddescription WHERE F_INFO_EXCHMARKET = 'USD' AND F_INFO_CORP_FUNDMANAGEMENTCOMP = '东方汇理资产管理香港有限公司';
SELECT S_INFO_NAME, MAX(S_INFO_INDEX_BASEPT) FROM aindexdescription;
SELECT S_INFO_WINDCODE, MAX(ITEM_AMOUNT) as Max_Amount FROM asharefinancialaccounts WHERE REPORT_PERIOD = "20171231"
SELECT MAX(AMOUNT) as highest_amount, S_INFO_WINDCODE, TITLE FROM ashareprosecution WHERE PRO_TYPE = '物业服务合同纠纷'
SELECT S_INFO_COMPNAME FROM asharemonthlyreportsofbrokers WHERE REPORT_PERIOD LIKE '201711%' AND NET_PROFIT_EXCL_MIN_INT_INC > 0;
SELECT SUM(AMOUNT) FROM top5byaccountsreceivable WHERE REPORT_PERIOD LIKE '2015%%';
SELECT S_INFO_WINDCODE, S_CODE, S_SNAME FROM cmfcodeandsname WHERE IS_COMMON = 1;
SELECT S_INFO_WINDCODE, AVG(S_INC_EXECPRI) as AVG_EXECPRI FROM ashareincexecqtypri GROUP BY S_INFO_WINDCODE
SELECT * FROM ashareplacementinfo WHERE S_INFO_WINDCODE = '603233.SH' ORDER BY TRADE_DT ASC;
SELECT * FROM asharemajorevent WHERE S_EVENT_CATEGORYCODE = '204005001'
SELECT S_INFO_WINDCODE, AVG(S_MQ_PCTCHANGE) AS Monthly_Yield FROM asharemonthlyyield WHERE TRADE_DT >= '20170101' AND TRADE_DT <= '20200531' GROUP BY S_INFO_WINDCODE ORDER BY Monthly_Yield DESC LIMIT 5
SELECT AVG(S_DQ_CLOSE) FROM chinaclosedfundeodprice WHERE S_INFO_WINDCODE = '160611.SZ' AND TRADE_DT BETWEEN '20180101' AND '20181231';
SELECT EVENT_TYPE, COUNT(DISTINCT COMP_ID) as Company_Count FROM ashareoperationevent GROUP BY EVENT_TYPE;
SELECT S_INFO_COMPCODE, MAX(S_FA_ASSETSTURN) as Max_AssetsTurnover, MIN(S_FA_ASSETSTURN) as Min_AssetsTurnover FROM asharefinancialindicator WHERE substr(REPORT_PERIOD, 0, 4) = '2017' GROUP BY S_INFO_COMPCODE;
SELECT F_INFO_FUNDMANAGER FROM chinamutualfundmanager WHERE F_INFO_MANAGER_STARTDATE = (SELECT MIN(F_INFO_MANAGER_STARTDATE) FROM chinamutualfundmanager) AND F_INFO_MANAGER_LEAVEDATE = (SELECT MIN(F_INFO_MANAGER_LEAVEDATE) FROM chinamutualfundmanager);
SELECT S_INFO_COMPCODE, MAX(END_DT), SUM(S_INFO_TOTALEMPLOYEES) FROM asharestaff GROUP BY S_INFO_COMPCODE
SELECT DISTINCT S_INFO_WINDCODE, ENTRY_DT FROM asharest WHERE S_TYPE_ST = '特别处理类型' AND REASON = 'S';
SELECT S_INFO_COMPCODE FROM asharenonprofitloss WHERE REPORT_PERIOD=(SELECT MAX(REPORT_PERIOD) FROM asharenonprofitloss) ORDER BY GOVERNMENT_SUBSIDY DESC LIMIT 10;
SELECT S_RIGHTSISSUE_ANNCEDATE, MAX(S_EXPECTED_FUND_RAISING) AS Maximum_Planned_Amount FROM asharerightissue GROUP BY S_RIGHTSISSUE_ANNCEDATE ORDER BY S_RIGHTSISSUE_ANNCEDATE ASC;
SELECT COMP_NAME, COUNT(*) AS NUM_OF_FUNDS FROM cmfaipinfo GROUP BY COMP_NAME ORDER BY NUM_OF_FUNDS DESC LIMIT 1;
SELECT DISTINCT S_INFO_WINDCODE FROM scfclause WHERE START_DT <= '20180101' AND (END_DT >= '20180101' OR END_DT = '99999999')
SELECT S_INFO_MANAGER_NAME, S_INFO_MANAGER_BIRTHYEAR, S_INFO_MANAGER_EDUCATION FROM cfundmanagement WHERE S_INFO_MANAGER_NATIONALITY = '汉';
SELECT S_INFO_WINDCODE, AVG(DEDAREDPRICE) as Average_Price FROM ipoinquirydetails GROUP BY S_INFO_WINDCODE ORDER BY Average_Price DESC LIMIT 1;
SELECT PRESIDENT FROM cfundintroduction ORDER BY S_INFO_TOTALEMPLOYEES DESC LIMIT 1;
SELECT REPORT_PERIOD, MAX(POLICY_PERSISTENCY_RATE_13M), MIN(POLICY_PERSISTENCY_RATE_13M) FROM ashareinsuranceindicator GROUP BY REPORT_PERIOD ORDER BY REPORT_PERIOD ASC;
SELECT S_INFO_WINDCODE, S_EVENT_ANNCEDATE, S_EVENT_CONTENT FROM asharemajorevent WHERE S_EVENT_ANNCEDATE = (SELECT MAX(S_EVENT_ANNCEDATE) FROM asharemajorevent WHERE S_INFO_WINDCODE = S_INFO_WINDCODE);
